### ISSUE TITLE
[Bug] A connected profile is considered not connected

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#452] opened 2019-12-03 08:46 UTC
# Bug Report

### System

- OS: Mac OS X
- OS Version: 10.13.6 (High Sierra)

### Browser

- Browser: Chrome
- Browser Version: 78.0.3904.108

### Maskbook

- Maskbook Version: 1.8.4
- Installation: GitHub Release [Maskbook.base.zip](https://github.com/DimensionDev/Maskbook/releases/tag/v1.8.4)
- Build Commit: `0e869f4`

### Expected Behavior

This Hint for Connecting Profile should not appear.

### Actual Behavior

Maskbook thinks that this profile, `twitter.com:skyneop`, is not connected. Actually, it has been connected already. Although Maskbook successfully retrieved the username from the webpage.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2139261/70033761-045b4200-15a8-11ea-9f86-2e71b5edce63.png">

### How To Reproduce

Note that the connection was made through database restoration, instead of fresh connecting.

Steps:

- Install
- Choose to Connect Twitter
- Open Dashboard
- Import Database Backup
- Visit twitter.com again

**Comment by neruthes** [comment] 2019-12-04 05:21
This bug remains in https://github.com/DimensionDev/Maskbook/releases/tag/v1.8.5

**Comment by Jack-Works** [comment] 2019-12-04 06:02
this component is rendered by the `AdditionalPostBox` so the title of it is "You have not setup yet".

it should be rendered by the `WelcomeBanner` component so the title will be "Welcome to Maskbook" and then cancelable.

The reason of using `AdditionalPostBox` is that the original designer(Misaka) of the twitter support says it's not easy to distinguish if the post box is active or not. If use both `WelcomeBanner` and `AdditionalPostBox`, there will be 2 `NotSetupYetPrompt` in the page.

**Comment by Tedko** [comment] 2019-12-06 15:08
Just reproduced this bug

**Comment by Jack-Works** [comment] 2019-12-07 15:11
Does this problem only appears in twitter?

**Comment by neruthes** [comment] 2019-12-07 15:13
Not found on Facebook yet. Need more tests.

**Comment by Tedko** [comment] 2019-12-07 15:17
Not found on fb yet as well.

**Comment by Tedko** [comment] 2019-12-20 18:45
any updts on this issue?

**Comment by guanbinrui** [comment] 2019-12-21 02:14
> any updts on this issue?

I will recheck this.

**Comment by guanbinrui** [comment] 2019-12-22 07:04
I can't reproduce this with new composition UI. In new composition UI `< NotSetupYetPrompt  />` component was wrapped in `<PostDialogHint />` component whose visibility depends on size of `currentIdentities`.

**Comment by Tedko** [comment] 2019-12-23 07:58
If can’t reproduce this issue it might be fixed already.

**Comment by Tedko** [comment] 2019-12-24 07:36
@guanbinrui i will close this issue. reopen if reproduced.

**Comment by neruthes** [comment] 2020-01-22 13:31
Recently reproduced by @Tedko.

**Comment by SunriseFox** [comment] 2020-01-22 13:32
Not the same problem.

**Closed by SunriseFox** 2020-01-22 13:32 UTC
Labels: Network: twitter.com, Priority: P2 (Important), Type: Bug

**Comment by neruthes** [comment] 2020-01-22 16:57
@SunriseFox Would you track the bug in another issue, please?

**Comment by SunriseFox** [comment] 2020-01-23 03:43
The one noticed is related to 
1. background page error detection and self-recovery
2. background page and content script's communication efficiency on a very large amount of data
You may open another issue to track them if critical

**Comment by neruthes** [comment] 2020-01-23 11:07
Tracked in #686.
