### ISSUE TITLE
[Crash] Error: Unreachable case:64

### ISSUE THREAD

**Issue by taosue** [DimensionDev/Maskbook#2197] opened 2021-01-08 14:38 UTC
I was Tao , then Maskbook report an error.

> Unreachable case:64

Error stack:
<pre>Error: Unreachable case:64
    at unreachable (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:768:11)
    at resolveLinkOnEtherscan (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:20304:85)
    at WalletStatusDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:3620:179)
    at wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:167:137)
    at ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:287:49)
    at bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:269:22)
    at ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:439)
    at Sj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:299)
    at Mj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:257:493)
    at W (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.scheduler.chunk.js:34:197)</pre>

## Build information:

- Version: 1.22.3
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2021-01-05T14:51:07.482Z
- VERSION: v1.22.3

## Git ():

012251c5 (released) on tag "v1.22.3"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment] 2021-01-08 15:15
Duplicate of #2094

**Closed by septs** 2021-01-08 15:15 UTC
