### ISSUE TITLE
[Task] Investigate Inconsistencies in Initialization Import Logic

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Maskbook#918] opened 2020-03-27 08:10 UTC
## Metadata

Field | Value
--- | ---
Parent Task/Demand | -
Expected Delivery Date | 2020-W??-5

## Content

There are suspected to be some inconsistencies with Database Import Logic during Initialization.

Documentation: https://confluence.dimension.chat/pages/viewpage.action?pageId=2064444

Compare the current implementation with section «Workflow 1B: Core Init / Restore Backup».

**Comment by septs** [comment] 2020-04-01 06:20
Reference: #917

**Comment by septs** [comment] 2020-08-13 07:13
@guanbinrui the issue is fixed on new dashboard?

**Comment by guanbinrui** [comment] 2020-08-13 07:27
The inconsistencies logics compare to current impl:

+ 3. - vii - 2. There is no choose another dialog in current impl
+ 6. If (the database has 0 wallet): Maskbook automatically creates a wallet whose default name is the initial 6 characters of its wallet address.

**Closed** 2020-11-26 09:31 UTC
Labels: Non-Coding Task, Will Not Fix
