### ISSUE TITLE
[Bug] Remove `select eth mainnet` func on mobile (iOS) version

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2353] opened 2021-02-03 19:49 UTC
## Bug Report

This func is not needed for general users.

### System

- [ ] Windows

  - OS Version:

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [ ] Chrome

  - Mask Version:
  - Browser Version:

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [x] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

/_What happened?_/

**Comment by Tedko** [comment] 2021-02-03 19:50
tested on TF version

**Comment by jk234ert** [comment] 2021-02-05 02:16
Issue caused by integrating dev version maskbook js scripts into mobile app release binaries.
Fixed by replacing with release version

**Comment by jk234ert** [comment] 2021-02-05 05:20
Still have issues using release version, need further investigate

**Closed** 2021-02-07 02:22 UTC
Labels: Platform: iOS (WebExt-shim), Type: Bug
