### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading '0x863Ed6128a17a264BE6Dd61f8751e04028153dAC')

### ISSUE THREAD

**Issue by cravero6** [DimensionDev/Maskbook#8531] opened 2023-01-18 09:42 UTC
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading '0x863Ed6128a17a264BE6Dd61f8751e04028153dAC')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading '0x863Ed6128a17a264BE6Dd61f8751e04028153dAC')
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8493.js:584:51
  at getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6792.js:1145:89)
  at Object.useSyncExternalStore (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:499:74)
  at exports.useSyncExternalStore (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7201.js:2117:63)
  at exports.useSubscription (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/9514.js:2010:79)
  at useRecentTransactions (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8862.js:1133:91)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/9511.js:6143:75
  at tj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:479:151)
  at Jk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:512:172)
  at Ik (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:509:203)
  at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:508:176)
  at fn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:624:76)
  at cn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:606:78)
  at bn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:604:338)
  at Qm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:604:158)
  at Sm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:597:387)
  at Mm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:599:306)
  at hh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:430:105)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:594:273</pre>

## Build info
- Version: 2.17.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2023-01-17T09:37:01.716Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by Tedko** [comment] 2023-01-25 16:41
@wenluomask

**Comment by guanbinrui** [comment] 2023-02-13 03:16
Duplicate of #8622

**Closed as completed by guanbinrui** 2023-02-13 03:16 UTC
