### ISSUE TITLE
Restrict options to be within current network when adding recipients

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#357] opened 2019-11-04 19:14 UTC
<img width="1470" alt="Screen Shot 2019-11-04 at 23 32 37" src="https://user-images.githubusercontent.com/6687437/68149959-c4d61180-ff79-11e9-9e9c-a4e29134a100.png">

<img width="1470" alt="Screen Shot 2019-11-05 at 03 12 01" src="https://user-images.githubusercontent.com/6687437/68150159-1da5aa00-ff7a-11e9-87f3-c6cded5fd186.png">
<img width="1470" alt="Screen Shot 2019-11-05 at 03 12 19" src="https://user-images.githubusercontent.com/6687437/68150160-1ed6d700-ff7a-11e9-9127-856456083704.png">

For the examples above: suji.yan.me @ facebook.com and suji_yan @ twitter.com are same person/identity on different social networks (with same fingerprint). Better ignore the same identity here, otherwise the users might be confused.

**Comment by Jack-Works** [comment] 2019-11-05 07:12
That's strange. Maskbook will query the current network only

**Comment by Tedko** [comment] 2019-11-05 07:13
Yes strange.
You can check the current twitter test ver.

**Comment by SunriseFox** [comment] 2019-11-09 03:29
Could not reproduce this on our latest develop branch. Maybe it has been solved sometime.  After #364 being merged, we could have a try again to see if it persists.

**Comment by Tedko** [comment] 2019-11-15 11:29
> Could not reproduce this on our latest develop branch. Maybe it has been solved sometime. After #364 being merged, we could have a try again to see if it persists.

@SunriseFox  can you reproduce this? if not let's close this issue.

**Closed** 2019-11-25 02:16 UTC
Labels: Component: Multiple Network, Type: Bug, Type: Enhancement, Type: UI
