### ISSUE TITLE
Scroll on iOS device

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Maskbook#302] opened 2019-10-21 07:48 UTC
See: https://stackoverflow.com/questions/47244002/make-wkwebview-real-fullscreen-on-iphone-x-remove-safe-area-from-wkwebview

related #301

**Comment by Tedko** [comment] 2019-11-12 19:15
Assign to @MainasuK  but the priority of this is not high

**Comment by MainasuK** [comment] 2019-11-14 07:36
@Jack-Works Need modify the native layout constraint?

**Comment by Jack-Works** [comment] 2019-11-15 14:03
> @Jack-Works Need modify the native layout constraint?

no need.

**Comment by Tedko** [comment] 2020-02-26 03:18
Let's prioritise this one @MainasuK

**Comment by MainasuK** [comment] 2020-02-26 03:19
@Jack-Works Need modify the native layout constraint or something?

**Comment by MainasuK** [comment] 2020-02-26 03:20
> Let's prioritise this one @MainasuK

Properly I can't do anything about that.

**Comment by Tedko** [comment] 2020-02-26 03:40
This problem needs to be fixed on front end side?

**Comment by MainasuK** [comment] 2020-02-26 03:45
I'm guess it is a CSS issue. @Jack-Works not request the native side change.
@Jack-Works please post your comment.

**Comment by Jack-Works** [comment] 2020-02-26 04:31
Sorry I forgot what excatly the problem is. Is there a screenshot for that?

**Comment by Tedko** [comment] 2020-02-26 04:37
> Sorry I forgot what excatly the problem is. Is there a screenshot for that?

I dont remember either..
Maybe just dismiss this issue.

**Comment by Tedko** [comment] 2020-03-01 05:27
I will close this issue since @Jack-Works dont really remember what’s the problem is, and seems like we haven’t encountered it recently.

**Closed by Tedko** 2020-03-01 05:27 UTC
Labels: Platform: iOS (WebExt-shim), Priority: P4 (Do when free)
