### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading '0xa13d0DF9075C4d61CeE4F3051d30215e32E61E76')

### ISSUE THREAD

**Issue by shanscar** [DimensionDev/Maskbook#8550] opened 2023-01-21 13:27 UTC
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading '0xa13d0DF9075C4d61CeE4F3051d30215e32E61E76')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading '0xa13d0DF9075C4d61CeE4F3051d30215e32E61E76')
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8493.js:584:51
  at getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6792.js:1145:89)
  at Object.Jj [as useSyncExternalStore] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:486:35)
  at exports.useSyncExternalStore (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7201.js:2117:63)
  at exports.useSubscription (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6631.js:1991:79)
  at useRecentTransactions (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8907.js:640:91)
  at useToolbox (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.2147.js:3068:86)
  at ToolboxHintForWallet (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.2147.js:3013:96)
  at tj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:479:151)
  at Jk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:512:172)
  at fn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:620:88)
  at cn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:606:78)
  at bn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:604:338)
  at Qm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:604:158)
  at Sm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:597:387)
  at Mm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:599:306)
  at hh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:430:105)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:594:273</pre>

## Build info
- Version: 2.17.4
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2023-01-19T10:14:17.711Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by guanbinrui** [comment] 2023-02-13 03:14
Duplicate of #8622.

**Closed as completed by guanbinrui** 2023-02-13 03:14 UTC
