### ISSUE TITLE
[Crash] Error: Invalid Username

### ISSUE THREAD

**Issue by ovicenzo** [DimensionDev/Maskbook#2865] opened 2021-04-16 02:58 UTC
I was *doing something...*, then Mask report an error.

> Invalid Username

Error stack:

<pre>construct@[native code]
user-script:7:4623:49
getPostUrlAtTwitter@https://mobile.twitter.com/home:790:24
RedPacketInPost@https://mobile.twitter.com/home:38395:77
ai@https://mobile.twitter.com/:238:138
Gk@https://mobile.twitter.com/:361:98
Fk@https://mobile.twitter.com/:350:24
Ck@https://mobile.twitter.com/:349:372
uk@https://mobile.twitter.com/:349:232
ok@https://mobile.twitter.com/:338:471
ok@[native code]
I@https://mobile.twitter.com/home:25975:204
https://mobile.twitter.com/home:25976:177</pre>

## Build info
- Version: 1.29.12
- NODE_ENV: production
- STORYBOOK: false
- target: safari
- build: stable
- architecture: app
- firefoxVariant: false
- resolution: mobile
- BUILD_DATE: 2021-03-17T09:06:37.438Z
- VERSION: v1.29.11-109-g625ea023

## Git (*):

625ea023 (master) on tag "v1.29.11"
https://github.com/DimensionDev/Maskbook

**Comment by septs** [comment] 2021-04-16 03:00
Duplicate of #2861

**Closed by septs** 2021-04-16 03:00 UTC
