### ISSUE TITLE
[Bug] Cannot fetch pub key on twitter

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#467] opened 2019-12-04 14:20 UTC
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser: Chrome / Firefox
- Browser Version: Latest stable ver

### Maskbook

- Maskbook Version: Latest Chrome/FF store ver
- Installation: Store
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info

Cannot fetch pub key of encrypted content sender

<img width="1269" alt="Screen Shot 2019-12-04 at 22 17 45" src="https://user-images.githubusercontent.com/6687437/70149896-fc082180-16e3-11ea-87a8-8e068e141750.png">

Also maskbook will try ~10 times to fetch the key. Maybe we should reduce the times of trying. it's annoying.

### Expected Behavior

Able to fetch the key and try to decrypt the content.

### Actual Behavior

See the pic above.

Also https://dimension.chat/group/maskbook?msg=4f6WPmC7Hds5RWk9v in rocket chat

### How To Reproduce

Install maskbook and finish setup on twitter. Goto https://twitter.com/differui

**Comment by Tedko** [comment] 2019-12-04 14:26
Also, if Maskbook failed to find pub key of content a' from User A, Maskbook should not keep trying to find content a'' send by same user A @guanbinrui  Otherwise it's wasting time

**Comment by Tedko** [comment] 2019-12-04 14:28
Expect this to be fixed within tmr

**Comment by guanbinrui** [comment] 2019-12-05 06:02
Duplicate of #465

**Closed by guanbinrui** 2019-12-05 06:02 UTC
Labels: Network: twitter.com, Priority: P1 (Now), Type: Bug
