### ISSUE TITLE
[Bug] Installing the Mask extension in the Brave browser makes the text of some tweets invisible.

### ISSUE THREAD

**Issue by newt0** [DimensionDev/Maskbook#9221] opened 2023-04-02 12:13 UTC
### How to reproduce?

1. Install Mask extension in Brave browser
2. Link your Mask and Twitter accounts

### What happened?
In Brave with the Mask extension, the font-color of the text in some tweets turns black and is not visible.

Brave
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56229817/229351823-d720962f-a602-4eb3-8ba7-7d418d0b88cf.png">

Brave Sercret Mode
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/56229817/229351951-5d483268-12dd-4704-b2e1-1cf888b783ff.png">

Chrome
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/56229817/229351837-9d1a909e-bb86-4d45-94cd-1087363c9efc.png">

■ This occurs in the following environments
- Macbook Pro 13-inch, M1, 2020
- Ventura 13.2.1
- Latest Brave Browser
- Latest Mask Extension
- Japan, Tokyo

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)

**Comment by Jack-Works** [comment] 2023-04-03 18:23
looks like it is caused by the dark mode detection wrong... Changing your twitter to light mode can temporally be a workaround. sorry for the inconvenience!

**Comment by hanszhoou** [comment] 2023-05-19 03:02
@newt0 Fixed by v2.20.0

<img width="1431" alt="image" src="https://github.com/DimensionDev/Maskbook/assets/63733714/2780bc09-168e-493b-8b79-3feda8d329f1">

**Closed as completed by hanszhoou** 2023-05-19 03:02 UTC
Labels: Type: Bug
