### ISSUE TITLE
[Bug] Some token is unable to load trending at the first time (Uniswap Info)

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2912] opened 2021-04-19 16:41 UTC
### How to reproduce?

1. Reinstall and set up a fresh Mask extension.
2. Search a token only available on Uniswap Info. E.g., go to https://twitter.com/search?q=%24test&src=typed_query.
3. The trending board is blocking at the loading stage.

### What happened?

![image](https://user-images.githubusercontent.com/52657989/115272422-f728fe00-a170-11eb-8465-e2a636e3a93a.png)

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by UncleBill** [comment] 2021-04-20 07:01
I can't reproduce, see https://share.getcloudapp.com/E0uYKG6q

**Comment by UncleBill** [comment] 2021-04-21 02:38
Is this fixed by https://github.com/DimensionDev/Maskbook/pull/2906 already?

**Closed** 2021-07-05 12:27 UTC
Labels: Type: Bug, Will Not Fix
