### ISSUE TITLE
[Crash] Error: Private key must be 32 bytes long

### ISSUE THREAD

**Issue by LonelyGypsie** [DimensionDev/Maskbook#5601] opened 2022-02-01 15:22 UTC
I was *doing something...*, then Mask reports an error.

> Private key must be 32 bytes long

Error stack:

<pre>sign@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/npm.web3-eth-accounts.js:793:15
RedPacket@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/chunk.1950.js:1854:176
Ch@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/npm.react-dom.js:171:137
gk@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/npm.react-dom.js:294:29
fk@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/npm.react-dom.js:282:24
ek@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/npm.react-dom.js:281:371
Vj@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/npm.react-dom.js:281:229
Pj@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/npm.react-dom.js:270:476
J@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/521.js:19512:204
R@moz-extension://37b86029-3ef3-4d29-bf0a-12558ee5d847/js/521.js:19513:123
</pre>

## Build info
- Version: 1.36.4
- NODE_ENV: production
- target: firefox
- build: stable
- architecture: app
- firefoxVariant: geckoview
- resolution: mobile
- BUILD_DATE: 2021-09-01T08:41:16.657Z
- VERSION: v1.29.12-812-gdb37692ed

## Git ():

db37692ed (released) on tag "v1.36.4"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment] 2022-02-06 07:33
Duplicate of #5600

**Closed as completed by septs** 2022-02-06 07:33 UTC
