### ISSUE TITLE
[Bug] UI - @xx on twitter disappeared in Mask rendered tweet

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#3042] opened 2021-04-27 16:15 UTC
## Bug Info

<img width="1235" alt="Screen Shot 2021-04-28 at 00 13 01" src="https://user-images.githubusercontent.com/6687437/116276139-cb33fb00-a7b6-11eb-85c7-c34bc71c966c.png">
<img width="1235" alt="Screen Shot 2021-04-28 at 00 13 08" src="https://user-images.githubusercontent.com/6687437/116276143-cbcc9180-a7b6-11eb-86dd-65773279fe69.png">

https://twitter.com/orabelart/status/1386415007399698435

Might be the same bug as the URL disappear 

### How to reproduce?

1.
2.
3.

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

**Comment by guanbinrui** [comment] 2021-04-28 03:46
duplicate of #3010

**Closed** 2021-04-28 03:46 UTC
Labels: Priority: P0 (Emergency), Type: Bug
