### ISSUE TITLE
[Bug] Display incorrect display

### ISSUE THREAD

**Issue by tiaramoe** [DimensionDev/Maskbook#3069] opened 2021-05-01 06:16 UTC
## Bug Info 

The content of youtu.be is lost when youtu.be link and image are included in Twitter. 

![2021-05-01 2.14.12.png](https://i.loli.net/2021/05/01/25D6Uw1zQ4NJGTo.png) 

### How to reproduce? 

Send a public raw tweet that includes an image and a link with youtu.be 

### What happened? 

The link of youtu.be disappears and does not display normally 

 
 

## Environment 

Chrome  

### Mask Version: 

v1.31.6 

- [x] (Browser) Installed from the extension store (version: ) 

- [ ] (App) Installed from the app store (version: ) 

- [ ] master branch 

- [ ] Build of version/commit hash: 

 
 

(Please write down build command/flags if there is anything special) 

 
 

### System 

 
 

  

- [x] Windows 10 

- [ ] Mac OS X Catalina 

- [ ] Linux:  

 
 

### Platform/Browser 

 
 

  

- [x] Latest Chrome (stable channel) 

- [ ] Latest Firefox (stable channel) 

- [ ] Android 11 

- [ ] iOS 14

**Comment by guanbinrui** [comment] 2021-05-01 06:20
Duplicate of #3010

**Closed by guanbinrui** 2021-05-01 06:20 UTC
Labels: Type: Bug
