### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading '0x1990859eE78aa9713A0A6765C1D4e06A7B888888')

### ISSUE THREAD

**Issue by xiazhiming** [DimensionDev/Maskbook#8109] opened 2022-11-24 07:20 UTC
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading '0x1990859eE78aa9713A0A6765C1D4e06A7B888888')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading '0x1990859eE78aa9713A0A6765C1D4e06A7B888888')
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8493.js:545:51
  at getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/4114.js:1690:20)
  at exports.useSubscription (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6872.js:1572:221)
  at useRecentTransactions (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/706.js:482:91)
  at useToolbox (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8133.js:3083:86)
  at ToolboxHintForWallet (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8133.js:3028:96)
  at mj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:455:137)
  at Ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:489:171)
  at Um (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:595:88)
  at Tm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:580:112)</pre>

## Build info
- Version: 2.16.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-11-18T16:27:59.322Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by guanbinrui** [comment] 2023-02-13 03:24
Duplicate of #8622

**Closed as completed by guanbinrui** 2023-02-13 03:24 UTC
