### ISSUE TITLE
[Crash] TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by nkiki** [DimensionDev/Maskbook#2203] opened 2021-01-09 04:59 UTC
I was ________, then Maskbook report an error.

> Cannot read property 'replace' of undefined

Error stack:
<pre>TypeError: Cannot read property 'replace' of undefined
    at Object.strip0x (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.chunk.js:6376:16)
    at isValidFormat (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.chunk.js:154:21)
    at Function.isValid (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.chunk.js:116:14)
    at createContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:1755:68)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:1848:72
    at Object.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:183:60)
    at push.1047.exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react.chunk.js:76:414)
    at useContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:1848:65)
    at useBalanceCheckerContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/options-page.js:1705:54)
    at useTokensBalance (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/options-page.js:1721:36)</pre>

## Build information:

- Version: 1.22.3
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2021-01-05T14:51:07.482Z
- VERSION: v1.22.3

## Git ():

012251c5 (released) on tag "v1.22.3"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment] 2021-01-10 16:08
Duplicate of #2025

**Closed by septs** 2021-01-10 16:08 UTC
