### ISSUE TITLE
[Crash] Error: Unreachable case:64

### ISSUE THREAD

**Issue by nkiki** [DimensionDev/Maskbook#2146] opened 2020-12-25 07:43 UTC
I was ________, then Maskbook report an error.

> Unreachable case:64

Error stack:
<pre>Error: Unreachable case:64
    at unreachable (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:768:11)
    at resolveLinkOnEtherscan (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:20304:85)
    at WalletStatusDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:3620:179)
    at wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:167:137)
    at ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:287:49)
    at bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:269:22)
    at ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:439)
    at Sj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:299)
    at Kj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:261:260)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:131:115</pre>

## Build information:

- Version: 1.22.2
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2020-12-18T05:01:59.118Z
- VERSION: v1.22.2

## Git ():

1e3b6966 (released) on tag "v1.22.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment] 2020-12-25 08:13
duplicate of #2094

**Closed by septs** 2020-12-25 08:13 UTC
