### ISSUE TITLE
[Bug] Connecting to MetaMask under My Wallets doesn't work in Brave

### ISSUE THREAD

**Issue by easeev** [DimensionDev/Maskbook#2421] opened 2021-02-19 18:34 UTC
### System

- [x] Windows

  - OS Version: 10

- [ ] Mac OS X

  - OS Version:

- [ ] Linux

  - Linux Distribution:
  - OS Version:

### Platform/Browser

- [x] Brave

  - Mask Version: 1.27.4
  - Browser Version: 1.20.103

- [ ] Firefox

  - Mask Version:
  - Browser Version:

- [ ] Android

  - Mask Version:
  - Android Version:

- [ ] iOS
  - Mask Version:
  - iOS Version:

### Build Variant

- Where do you get Mask?
  - [x] Store
  - [ ] ZIP
  - [ ] Self-Compiled
    - Build Commit: /_Optionally attach a Commit ID, if it is from an pre-release branch head_/

### Actual Behavior

Connecting to MetaMask under My Wallets doesn't work in Brave

```
npm.async-call-rpc.js:457 Error: Must provide a Node.js-style duplex stream.(-1) @hxgiku7ssegError: Must provide a Node.js-style duplex stream.    at new MetaMaskInpageProvider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.npm.metamask.inpage-provider.js:79:13)    at createMetaMaskProvider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5644.js:50:58)    at async createProvider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5644.js:4413:16)    at async createWeb3 (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5644.js:4422:16)    at async Object.requestAccounts (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5644.js:4431:18)    at async Object.connectMetaMask (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.1623.js:112:22)    at async onRequest (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:431:28)    at async rawMessageReceiver (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:482:34)    at async chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service.js:1605:28
onResponse @ npm.async-call-rpc.js:457
handleSingleMessage @ npm.async-call-rpc.js:572
rawMessageReceiver @ npm.async-call-rpc.js:482
async function (async)
rawMessageReceiver @ npm.async-call-rpc.js:480
(anonymous) @ npm.async-call-rpc.js:534
(anonymous) @ npm.dimensiondev.holoflows-kit.js:777
emit @ npm.dimensiondev.holoflows-kit.js:777
(anonymous) @ npm.dimensiondev.holoflows-kit.js:4888
async function (async)
(anonymous) @ npm.dimensiondev.holoflows-kit.js:4884
(anonymous) @ npm.dimensiondev.holoflows-kit.js:777
emit @ npm.dimensiondev.holoflows-kit.js:777
(anonymous) @ npm.dimensiondev.holoflows-kit.js:4946
5695.js:50517 Uncaught (in promise) Error: Must provide a Node.js-style duplex stream.
    at new MetaMaskInpageProvider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.npm.metamask.inpage-provider.js:79:13)
    at createMetaMaskProvider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5644.js:50:58)
    at async createProvider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5644.js:4413:16)
    at async createWeb3 (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5644.js:4422:16)
    at async Object.requestAccounts (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5644.js:4431:18)
    at async Object.connectMetaMask (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.1623.js:112:22)
    at async onRequest (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:431:28)
    at async rawMessageReceiver (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:482:34)
    at async chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service.js:1605:28
    аt AsyncCall (rpc) 
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:50506:81
    at onClick (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:50519:398)
    at Object.Mb (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:117:133)
    at Sb (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:117:287)
    at Tb (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:117:341)
    at Re (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:165:68)
    at je (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:166:380)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:178:119
    at Gb (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:372:182)
```

**Comment by Jack-Works** [comment] 2021-02-20 02:49
Is it caused by the metamask provider doesn't list the id of the metamask extension on brave? cc @guanbinrui

**Comment by Tedko** [comment] 2021-03-12 05:24
should we contact MM team for support?

**Comment by Tedko** [comment] 2021-03-12 05:24
btw @zhouhanseng is our PR to MM team been merged?

**Comment by zhouhanseng** [comment] 2021-03-12 05:31
@Tedko We reported an issue https://github.com/MetaMask/metamask-extension/issues/10368 (not PR) to MM team, they haven't fixed it.

**Closed** 2021-06-17 10:54 UTC
Labels: Type: Bug, Will Not Fix
