### ISSUE TITLE
[Crash] Error: Unreachable case:13881

### ISSUE THREAD

**Issue by imran201111** [DimensionDev/Maskbook#2169] opened 2021-01-02 17:14 UTC
I was ________, then Maskbook report an error.

> Unreachable case:13881

Error stack:
<pre>Error: Unreachable case:13881
    at unreachable (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:768:11)
    at resolveLinkOnEtherscan (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:20304:85)
    at WalletStatusDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:3620:179)
    at wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:167:137)
    at gi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:191:158)
    at ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:288:475)
    at bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:269:22)
    at ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:439)
    at Sj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:299)
    at Mj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:257:493)</pre>

## Build information:

- Version: 1.22.2
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2020-12-18T05:01:59.118Z
- VERSION: v1.22.2

## Git ():

1e3b6966 (released) on tag "v1.22.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment] 2021-01-02 19:59
https://github.com/DimensionDev/Maskbook/blob/bb7353bc531bdf108349982cab9d8110d3227dcc/packages/maskbook/src/web3/pipes.ts#L68-L83

**Comment by septs** [comment] 2021-01-02 21:55
Duplicate of #2094

**Closed by septs** 2021-01-02 21:55 UTC
