### ISSUE TITLE
[Crash] Error: Private key must be 32 bytes long

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#5602] opened 2022-02-01 18:22 UTC
I went to this tweet included lucky drop plugin( https://twitter.com/Syahnara11/status/1488456410379976704 ), then Mask reports an error.

> Private key must be 32 bytes long

Error stack:

<pre>Error: Private key must be 32 bytes long
    at Accounts.sign (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/npm.web3-eth-accounts.js:365:15)
    at RedPacket (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/chunk.3898.js:5869:176)
    at Mh (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/npm.react-dom.js:172:137)
    at Gk (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/npm.react-dom.js:295:386)
    at Fk (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/npm.react-dom.js:285:22)
    at Ek (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/npm.react-dom.js:284:410)
    at sk (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/npm.react-dom.js:284:270)
    at xk (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/npm.react-dom.js:275:418)
    at qk (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/npm.react-dom.js:273:421)
    at J (chrome-extension://kengepkenpjnjlcgolghhaacplfekbka/js/4975.js:3049:203)</pre>

## Build info
- Version: 2.3.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-01-30T10:20:04.920Z
- VERSION: v1.29.12-1851-g2ca722521

## Git (*):

2ca722521 (develop) on tag "v2.1.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment] 2022-02-06 07:33
Duplicate of #5600

**Closed as completed by septs** 2022-02-06 07:33 UTC
