### ISSUE TITLE
[Crash] TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Tristin-0** [DimensionDev/Maskbook#2211] opened 2021-01-10 08:07 UTC
I was ________, then Mask report an error.

> Cannot read property 'replace' of undefined

Error stack:
<pre>TypeError: Cannot read property 'replace' of undefined
    at Object.strip0x (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.js:2802:16)
    at isValidFormat (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.js:154:21)
    at Function.isValid (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.js:116:14)
    at createContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7689.js:19310:65)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7689.js:19403:65
    at Object.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:243:60)
    at exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react.js:50:414)
    at useContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7689.js:19403:58)
    at useBalanceCheckerContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/options-page.js:3809:46)
    at useTokensBalance (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/options-page.js:3825:36)</pre>

## Build information:

- Version: 1.23.0
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-01-08T15:11:14.128Z
- VERSION: v1.22.3-80-g629f0c27

## Git (*):

629f0c27 (released) on tag "v1.23.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment] 2021-01-10 16:08
Duplicate of #2025

**Closed by septs** 2021-01-10 16:08 UTC
