### ISSUE TITLE
[Crash] Error: Unreachable case:2

### ISSUE THREAD

**Issue by LeeChunHao2000** [DimensionDev/Maskbook#2212] opened 2021-01-10 16:41 UTC
I was ________, then Mask report an error.

> Unreachable case:2

Error stack:
<pre>unreachable@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/options-page.js:8786:11
resolveLinkOnEtherscan@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/76.js:20326:80
WalletStatusDialog@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/76.js:16142:161
wh@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:227:137
ck@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:347:49
bk@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:329:24
ak@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:328:441
Sj@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:328:299
Kj@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:321:260
cg/<@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:191:115
60053/exports.unstable_runWithPriority@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.scheduler.js:23:343
$f@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:190:325
cg@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:191:63
bg@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:190:428
Uj@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:322:114
Fb@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:372:129
jd@moz-extension://69b3c7fa-1b70-4ac0-acd7-09f3410d3b44/js/npm.react-dom.js:139:377
</pre>

## Build information:

- Version: 1.23.2
- NODE_ENV: production
- STORYBOOK: false
- target: firefox
- build: stable
- architecture: web
- firefoxVariant: fennec
- resolution: desktop
- BUILD_DATE: 2021-01-10T05:23:14.189Z
- VERSION: v1.23.2

## Git ():

c86ff7f6 (released) on tag "v1.23.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment] 2021-01-10 16:45
Duplicate of #2094

**Closed by septs** 2021-01-10 16:45 UTC
