### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by smopuim369** [DimensionDev/Maskbook#8396] opened 2023-01-04 10:03 UTC
# I was *scrolling...*, then Mask reports an error.

> Cannot read properties of undefined (reading 'match')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'match')
  at visitor (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6592.js:207:46)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6592.js:4051:26
  at Array.flatMap (<anonymous>)
  at visitEachTypedMessageChild (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6592.js:4050:34)
  at visitor (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6592.js:234:103)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6592.js:3860:54
  at Array.reduce (<anonymous>)
  at composed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6592.js:3860:37)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6592.js:3863:50
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8696.js:445:26</pre>

## Build info
- Version: 2.16.4
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-12-19T13:39:05.780Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by Jack-Works** [comment] 2023-02-16 14:24
I believe it comes in the https://github.com/DimensionDev/Maskbook/blob/b4b5a819ed9eba543935b9f5d8993a97413c858a/packages/mask/shared-ui/TypedMessageRender/transformer.ts#L69, but I have no idea why. Can you provide information about which post cause this crash? thanks!

**Comment by Tedko** [comment] 2023-03-19 19:36
should we close this is not able to reproduce @wenluomask

**Closed as completed** 2023-03-20 00:03 UTC
