### ISSUE TITLE
[Bug] Cannot fetch pub key when user don't have avatar & header phx

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#477] opened 2019-12-06 15:30 UTC
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser: Chrome & Firefox
- Browser Version: latest stable ver

### Maskbook

- Maskbook Version: v1.8.7 from Chrome store
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info
See the pic below
### Expected Behavior

/* Write the expected behavior here. */
Able to fetch the pub key
### Actual Behavior

![Screen Shot 2019-12-06 at 23 23 18](https://user-images.githubusercontent.com/6687437/70334083-b1bba780-187f-11ea-80c4-7753ca507f43.png)
<img width="678" alt="Screen Shot 2019-12-06 at 23 23 59" src="https://user-images.githubusercontent.com/6687437/70334088-b2ecd480-187f-11ea-8435-0f6edf726fca.png">

/* Write the actual behavior here. */

### How To Reproduce
Visit https://twitter.com/infxyz (without header photo and avatar phx)

Related withh #465

**Comment by guanbinrui** [comment] 2019-12-09 14:24
This issue caused by #465 which was fixed in #466 but still waiting for next release. Here is what the tweet looks after applying the patch.

![image](https://user-images.githubusercontent.com/52657989/70443031-5af9dc00-1ad2-11ea-946f-0efff2cb6e3e.png)

**Comment by Tedko** [comment] 2019-12-09 17:08
> This issue caused by #465 which have been fixed in #466 but still waiting for next release. Here is what the tweet looks after applying the patch.
> 
> ![image](https://user-images.githubusercontent.com/52657989/70443031-5af9dc00-1ad2-11ea-946f-0efff2cb6e3e.png)

👍🏻👍🏻

**Closed** 2019-12-09 17:09 UTC
Labels: Network: twitter.com, Priority: P2 (Important), Type: Bug
