### ISSUE TITLE
[Crash] Error: Unreachable case:56

### ISSUE THREAD

**Issue by msk1789** [DimensionDev/Maskbook#2272] opened 2021-01-21 13:52 UTC
I was ________, then Mask report an error.

> Unreachable case:56

Error stack:
<pre>unreachable@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/options-page.js:8830:20
resolveLinkOnEtherscan@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/3756.js:20705:80
WalletStatusDialog@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/3756.js:16577:161
wh@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:227:138
ck@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:347:51
bk@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:329:24
ak@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:328:441
Sj@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:328:301
Mj@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.react-dom.js:317:495
Mj@[native code]
W@holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.scheduler.js:21:198
holoflows-extension://eofkdgkhfoebecmamljfaepckoecjhib/js/npm.scheduler.js:18:297</pre>

## Build information:

- Version: 1.23.2
- NODE_ENV: production
- STORYBOOK: false
- target: safari
- build: stable
- architecture: app
- firefoxVariant: false
- resolution: mobile
- BUILD_DATE: 2021-01-15T08:15:12.205Z
- VERSION: v1.23.1-33-ga056d5ee

## Git (*):

a056d5ee (master) on tag "v1.23.1"
https://github.com/DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment] 2021-01-21 14:05
Duplicate of #2094, it is already fixed in the next version IMO, thanks for your report

**Closed by Jack-Works** 2021-01-21 14:05 UTC
