### ISSUE TITLE
[Bug] UI display error

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#46] opened 2019-05-28 16:27 UTC
![61448915_2354832304539921_2259555708578037760_n](https://user-images.githubusercontent.com/6687437/58494801-835e6080-81a8-11e9-8e91-5878903efee6.jpg)
<img width="565" alt="Screen Shot 2019-05-29 at 00 26 10" src="https://user-images.githubusercontent.com/6687437/58494803-83f6f700-81a8-11e9-9f18-14c13a4bf9c7.png">

Not reproduced on my side yet.

**Comment by Jack-Works** [comment] 2019-05-29 02:54
不能升級嗎……

**Comment by Jack-Works** [comment] 2019-05-29 02:57
And by the way, due to the bug of tab crash in Chrome 74, I have set the minimum required Chrome version to 75. Should I roll back this?

**Comment by Tedko** [comment] 2019-05-29 03:00
So if you send it to 75, can 74 still install it through chrome web store?

**Comment by Jack-Works** [comment] 2019-05-29 03:09
I don't know about new users. But old users cannot get updates. Ok, I should roll back this.

**Comment by Jack-Works** [comment] 2019-05-29 03:26
![image](https://user-images.githubusercontent.com/5390719/58527284-a0c11800-8204-11e9-926e-ed30781fd050.png)

Doen't reproduce in Chrome 70

**Comment by Jack-Works** [comment] 2019-05-29 03:29
And in the master branch, I'm re-implementing the ConstructableStyleSheetsRenderer due to the breaking of JSS@^10.

**Comment by Tedko** [comment] 2019-05-29 07:14
will check if we can reproduce this later

**Comment by Jack-Works** [comment] 2019-05-29 14:12
I've rewrite the ConstructableStyleSheetsRenderer and the polyfill for ConstructableStyleSheets.

This problem should be impoved a lot now. (But there may still bugs).

**Comment by Jack-Works** [comment] 2019-05-30 06:40
Okay I resolved with Chrome 74

**Comment by Jack-Works** [comment] 2019-05-30 06:44
Closed by 05590cf30e5d3a96de6640a05c038a3d551cb9a7

**Closed by Jack-Works** 2019-05-30 06:44 UTC
Labels: bug

**Comment by Tedko** [comment] 2019-05-30 06:57
👍
